# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.12
    hooks:
      - id: uv-lock
      - id: uv-export
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        # Runs from the project venv. versions pinned by uv.lock.
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^e2e_tests
    -   id: django-tests
        name: django tests
        entry: sh scripts/pre-commit-django-tests.sh
        language: system
        pass_filenames: false


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-merge-conflict
        args: [--assume-in-merge]
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: pretty-format-json
        args: [--indent=4, --top-keys, "model,pk"]
        exclude: ^package-lock\.json$
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
        exclude: ^e2e_tests/
      # Run import order.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
        exclude: ^e2e_tests/
      # Run the formatter.
      - id: ruff-format
        exclude: ^e2e_tests/

-   repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        files: ^templates/.*\.html$
