[mypy]
strict = true
python_version = 3.13
# Prevents generic "# type: ignore" comments; require code like ignore[assignment].
# See https://mypy.readthedocs.io/en/stable/error_code_list2.html#code-ignore-without-code
enable_error_code = ignore-without-code

[mypy-allauth.*]
ignore_missing_imports = true

[mypy-environ]
# No typing yet; see https://github.com/joke2k/django-environ/issues/365
ignore_missing_imports = true

[mypy-django_filters.*]
ignore_missing_imports = true

[mypy-notifications.*]
ignore_missing_imports = true

[mypy-imagekit.*]
ignore_missing_imports = True

[mypy-ipware.*]
ignore_missing_imports = True

[mypy-pywebpush.*]
ignore_missing_imports = True

[mypy-py_vapid.*]
ignore_missing_imports = True
