[mypy]
strict = true
python_version = 3.13

[mypy-allauth.*]
ignore_missing_imports = true

[mypy-environ]
# No typing yet; see https://github.com/joke2k/django-environ/issues/365
ignore_missing_imports = true

[mypy-django_filters.*]
ignore_missing_imports = true

[mypy-notifications.*]
ignore_missing_imports = true

[mypy-imagekit.*]
ignore_missing_imports = True

[mypy-ipware.*]
ignore_missing_imports = True
