# Generated by Django 5.2 on 2025-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BorrowdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="groups/logos"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="groups/banners"
                    ),
                ),
                (
                    "membership_requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="If true, new members will require Moderator approval to join the group.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time at which the group was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time at which the group was last updated.",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_this_group", "Can view this Group"),
                    ("edit_this_group", "Can edit this Group"),
                    ("delete_this_group", "Can delete this Group"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_moderator", models.BooleanField(default=False)),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time at which the user joined the group.",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("BANNED", "Banned"),
                            ("ENDED", "Ended"),
                        ]
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        help_text="The date and time at which the membership status was last updated.",
                        null=True,
                    ),
                ),
                (
                    "status_changed_reason",
                    models.TextField(
                        help_text="The reason for which the status was last updated. May be useful in unfortunate cases of suspension / banning.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "trust_level",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                        help_text="The User's selected level of Trust for the given Group.",
                    ),
                ),
            ],
        ),
    ]
