# Generated by Django 5.2 on 2025-04-29 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowd_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowdgroup",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created the group.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="borrowdgroup",
            name="updated_by",
            field=models.ForeignKey(
                help_text="The last user who updated the group.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="borrowd_groups.borrowdgroup",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="borrowdgroup",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users in this group.",
                through="borrowd_groups.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
