# Generated by Django 5.2 on 2025-04-29 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("borrowd_groups", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="BorrowdGroup",
        ),
    ]
