# Generated by Django 5.2 on 2025-04-30 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time at which the user joined the group.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.TextField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="active",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="status_changed_at",
            field=models.DateTimeField(
                help_text="The date and time at which the membership status was last updated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="status_changed_reason",
            field=models.TextField(
                help_text=(
                    "The reason for which the status was last updated."
                    " May be useful in unfortunate cases of suspension / banning."
                ),
                max_length=500,
                null=True,
            ),
        ),
    ]
