# Generated by Django 5.2.1 on 2025-09-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowdgroup",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="borrowdgroup",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
