# Generated by Django 5.2.1 on 2025-11-15 15:22

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0003_alter_borrowdgroup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowdgroup",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="groups/banners/"
            ),
        ),
        migrations.AlterField(
            model_name="borrowdgroup",
            name="logo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="groups/logos/"
            ),
        ),
    ]
