# Generated by Django 5.2 on 2025-05-08 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0004_borrowdgroupobjectpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "group")},
        ),
    ]
