# Generated by Django 5.2.1 on 2026-02-11 10:53

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_membership_trust_level(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Membership = apps.get_model("borrowd_groups", "Membership")
    for membership in Membership.objects.all():
        if membership.trust_level == 3:
            membership.trust_level = 2
        elif membership.trust_level == 2:
            membership.trust_level = 1
        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0005_borrowdgroup_perms_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="trust_level",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "High")],
                help_text="The User's selected level of Trust for the given Group.",
            ),
        ),
        migrations.RunPython(update_membership_trust_level),
    ]
