# Generated by Django 5.2 on 2025-05-08 23:34

from django.conf import settings
from django.db import migrations, models

import borrowd_groups.models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0005_alter_membership_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="borrowdgroup",
            managers=[
                ("objects", borrowd_groups.models.BorrowdGroupManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_membership"
            ),
        ),
    ]
