# Generated by Django 5.2.1 on 2026-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0005_borrowdgroup_perms_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="trust_level",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "High")],
                help_text="The User's selected level of Trust for the given Group.",
            ),
        ),
    ]
