# Generated by Django 5.2 on 2025-05-13 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0006_alter_borrowdgroup_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowdgroup",
            options={
                "permissions": (
                    ("view_this_group", "Can view this Group"),
                    ("edit_this_group", "Can edit this Group"),
                    ("delete_this_group", "Can delete this Group"),
                )
            },
        ),
    ]
