# Generated by Django 5.2.1 on 2026-03-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0006_alter_membership_trust_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowdgroup",
            name="membership_requires_approval",
            field=models.BooleanField(
                default=True,
                help_text="New members require Moderator approval to join the group",
            ),
        ),
    ]
