# Generated by Django 5.2.13 on 2026-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0011_merge_20260414_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowdgroup",
            name="needs_moderator",
            field=models.BooleanField(
                default=False,
                help_text="True when the group has no moderator and needs one.",
            ),
        ),
    ]
