# Generated by Django 5.2.13 on 2026-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0012_backfill_item_view_perms_for_members"),
    ]

    operations = [
        # AlterField adds a default so the reverse (AddField) can populate
        # existing rows when rolling back to this migration.
        migrations.AlterField(
            model_name="membership",
            name="trust_level",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "High")], default=1
            ),
        ),
        migrations.RemoveField(
            model_name="membership",
            name="trust_level",
        ),
    ]
