# Generated by Django 5.2.13 on 2026-07-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowd_groups', '0012_backfill_item_view_perms_for_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='trust_level',
        ),
    ]
