# Generated by Django 5.2.13 on 2026-09-01 00:17

import django.core.validators
import imagekit.models.fields
from django.db import migrations

import borrowd.validators


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0013_remove_membership_trust_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowdgroup",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="groups/banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    borrowd.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowdgroup",
            name="logo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="groups/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    borrowd.validators.validate_image_size,
                ],
            ),
        ),
    ]
