# Generated by Django 5.2.13 on 2026-08-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_community_requests", "0001_initial"),
        ("borrowd_items", "0024_item_listing_type_alter_transaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityrequest",
            name="fulfilled_by_item",
        ),
        migrations.CreateModel(
            name="CommunityRequestResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_request_responses",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="borrowd_community_requests.communityrequest",
                    ),
                ),
            ],
        ),
    ]
