# Generated by Django 5.2.13 on 2026-08-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowd_community_requests",
            "0002_remove_communityrequest_fulfilled_by_item_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CANCELLED", "Cancelled"),
                    ("FULFILLED", "Fulfilled"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
