# Generated by Django 5.2.1 on 2025-09-15 21:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this beta code.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "num_uses",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of times this code can be used."
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Auto-generated 7-character alphanumeric code.",
                        max_length=7,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin user who created this beta code.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_beta_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who last updated this beta code.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_beta_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BetaSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beta_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="borrowd_beta.betacode",
                    ),
                ),
            ],
        ),
    ]
