# Generated by Django 5.2.1 on 2025-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_beta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betacode",
            name="name",
            field=models.CharField(
                help_text="A descriptive name for this beta code e.g. 'Social Media Campaign', 'Friend Referrals'.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
