# Generated by Django 5.2.13 on 2026-06-12 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (10, "Item requested"),
                            (15, "Item request accepted"),
                            (20, "Item request denied"),
                            (25, "Item notify when available"),
                            (30, "Item subscription"),
                            (35, "Item returned"),
                            (40, "Change to group membership"),
                            (45, "Group needs moderator"),
                        ]
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("APP", "In-App Notification"),
                            ("PUSH", "Push Notification"),
                            ("EMAIL", "Email"),
                        ],
                        default="APP",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns thoses preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
