# Generated by Django 5.2.1 on 2025-08-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ITEM_REQUESTED", "Item Requested"),
                            ("ITEM_REQUEST_ACCEPTED", "Item Request Accepted"),
                            ("ITEM_REQUEST_DENIED", "Item Request Denied"),
                            ("ITEM_RETURNED", "Item Returned"),
                            ("GROUP_MEMBER_JOINED", "Group Member Joined"),
                        ],
                        help_text="The type of notification being sent.",
                        max_length=50,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="List of channels through which this notification should be sent.",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(10, "Pending"), (20, "Sent"), (30, "Failed")],
                        default=10,
                        help_text="The current status of the notification.",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, help_text="The ID of the related object.", null=True
                    ),
                ),
                (
                    "context_data",
                    models.TextField(
                        blank=True,
                        help_text="JSON data with additional context for the notification.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the notification failed to send.",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this notification has been read by the recipient.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this notification was created.",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this notification was sent.",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The content type of the related object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user receiving the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
