# Generated by Django 5.2.13 on 2026-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("Item requested", "Item Requested"),
                    ("Item request accepted", "Item Request Accepted"),
                    ("Item request denied", "Item Request Denied"),
                    ("Item notify when available", "Item Notify When Available"),
                    ("Item subscription", "Item Subscription"),
                    ("Item returned", "Item Returned"),
                    ("Change to group membership", "Group Member Joined"),
                    ("Group needs moderator", "Group Needs Moderator"),
                ]
            ),
        ),
    ]
