# Generated by Django 5.2.13 on 2026-06-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_notifications", "0003_push_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    (
                        "Item requested",
                        "{requester_name} wants to borrow your {item_name}",
                    ),
                    (
                        "Item request accepted",
                        "Your request for {item_name} was accepted by {item_owner_name}",
                    ),
                    (
                        "Item request denied",
                        "Your request for {item_name} was declined",
                    ),
                    (
                        "Collection asserted",
                        "{requester_name} says they have collected {item_name}",
                    ),
                    (
                        "Collection confirmed",
                        "Collection of {item_name} has been confirmed",
                    ),
                    (
                        "Return asserted",
                        "{requester_name} says they have returned {item_name}",
                    ),
                    ("Return confirmed", "Return of {item_name} has been confirmed"),
                    (
                        "Item notify when available",
                        "{item_name} is now available to borrow",
                    ),
                    (
                        "Item subscription",
                        "{subscriber_name} wants to be notified when {item_name} is available",
                    ),
                    (
                        "A member joined a group you're part of",
                        "{new_member_name} joined {group_name}",
                    ),
                    ("Group needs moderator", "{group_name} needs a moderator"),
                    (
                        "Membership pending",
                        "{new_member_name} has requested to join {group_name}",
                    ),
                    (
                        "Membership approved",
                        "Your membership to {group_name} was approved",
                    ),
                    (
                        "Community request posted",
                        "A new community request was posted in {group_name}",
                    ),
                    (
                        "Community request fulfilled",
                        "A community request in {group_name} was fulfilled",
                    ),
                    (
                        "Request cancelled - borrower left",
                        "Your borrow request for {item_name} was cancelled",
                    ),
                    (
                        "Request cancelled - owner left",
                        "Your request for {item_name} was cancelled because the owner left",
                    ),
                    (
                        "Loan ended - owner left",
                        "Your loan of {item_name} has ended because the owner left",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
