# Generated by Django 5.2.13 on 2026-07-07 00:58

import itertools

from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

_NEW_NOTIFICATION_TYPES = [
    "GIVEAWAY_REQUEST_RECEIVED",
    "GIVEAWAY_REQUEST_APPROVED",
    "GIVEAWAY_REQUEST_DECLINED",
    "GIVEAWAY_COMPLETED",
]


def seed_giveaway_request_preferences(
    apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor
) -> None:
    NotificationPreference = apps.get_model(
        "borrowd_notifications", "NotificationPreference"
    )
    User = apps.get_model(settings.AUTH_USER_MODEL)

    user_ids = list(User.objects.values_list("id", flat=True))
    NotificationPreference.objects.bulk_create(
        [
            NotificationPreference(
                user_id=user_id,
                notification_type=notification_type,
                in_app_enabled=True,
                email_enabled=True,
                push_enabled=False,
            )
            for user_id, notification_type in itertools.product(
                user_ids, _NEW_NOTIFICATION_TYPES
            )
        ],
        batch_size=500,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowd_notifications",
            "0003_alter_notificationpreference_notification_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ITEM_REQUESTED", "Item Requested"),
                    ("ITEM_REQUEST_ACCEPTED", "Item Request Accepted"),
                    ("ITEM_REQUEST_DENIED", "Item Request Denied"),
                    ("COLLECTION_ASSERTED", "Collection Asserted"),
                    ("COLLECTION_CONFIRMED", "Collection Confirmed"),
                    ("RETURN_ASSERTED", "Return Asserted"),
                    ("RETURN_CONFIRMED", "Return Confirmed"),
                    ("ITEM_NOTIFY_WHEN_AVAILABLE", "Item Notify When Available"),
                    ("ITEM_SUBSCRIPTION", "Item Subscription"),
                    ("ITEM_RETURN_REQUESTED", "Item Return Requested"),
                    ("ITEM_DISPUTED", "Item Disputed"),
                    ("GROUP_MEMBER_JOINED", "Group Member Joined"),
                    ("GROUP_NEEDS_MODERATOR", "Group Needs Moderator"),
                    ("MEMBERSHIP_PENDING", "Membership Pending"),
                    ("MEMBERSHIP_APPROVED", "Membership Approved"),
                    ("COMMUNITY_REQUEST_POSTED", "Community Request Posted"),
                    ("COMMUNITY_REQUEST_FULFILLED", "Community Request Fulfilled"),
                    (
                        "REQUEST_CANCELLED_BORROWER_LEFT",
                        "Request Cancelled Borrower Left",
                    ),
                    ("REQUEST_CANCELLED_OWNER_LEFT", "Request Cancelled Owner Left"),
                    ("LOAN_ENDED_OWNER_LEFT", "Loan Ended Owner Left"),
                    ("GIVEAWAY_OFFER_SENT", "Giveaway Offer Sent"),
                    ("GIVEAWAY_ACCEPTED", "Giveaway Accepted"),
                    ("GIVEAWAY_DECLINED", "Giveaway Declined"),
                    ("GIVEAWAY_REQUEST_RECEIVED", "Giveaway Request Received"),
                    ("GIVEAWAY_REQUEST_APPROVED", "Giveaway Request Approved"),
                    ("GIVEAWAY_REQUEST_DECLINED", "Giveaway Request Declined"),
                    ("GIVEAWAY_COMPLETED", "Giveaway Completed"),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(
            seed_giveaway_request_preferences, migrations.RunPython.noop
        ),
    ]
