# Generated by Django 5.2.13 on 2026-09-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_notifications", "0006_seed_community_request_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ITEM_REQUESTED", "Item Requested"),
                    ("ITEM_REQUEST_ACCEPTED", "Item Request Accepted"),
                    ("ITEM_REQUEST_DENIED", "Item Request Denied"),
                    ("COLLECTION_ASSERTED", "Collection Asserted"),
                    ("COLLECTION_CONFIRMED", "Collection Confirmed"),
                    ("RETURN_ASSERTED", "Return Asserted"),
                    ("RETURN_CONFIRMED", "Return Confirmed"),
                    ("ITEM_NOTIFY_WHEN_AVAILABLE", "Item Notify When Available"),
                    ("ITEM_SUBSCRIPTION", "Item Subscription"),
                    ("ITEM_RETURN_REQUESTED", "Item Return Requested"),
                    ("ITEM_DISPUTED", "Item Disputed"),
                    ("GROUP_MEMBER_JOINED", "Group Member Joined"),
                    ("GROUP_NEEDS_MODERATOR", "Group Needs Moderator"),
                    ("MEMBERSHIP_PENDING", "Membership Pending"),
                    ("MEMBERSHIP_APPROVED", "Membership Approved"),
                    ("COMMUNITY_REQUEST_POSTED", "Community Request Posted"),
                    ("COMMUNITY_REQUEST_FULFILLED", "Community Request Fulfilled"),
                    (
                        "REQUEST_CANCELLED_BORROWER_LEFT",
                        "Request Cancelled Borrower Left",
                    ),
                    ("REQUEST_CANCELLED_OWNER_LEFT", "Request Cancelled Owner Left"),
                    ("LOAN_ENDED_OWNER_LEFT", "Loan Ended Owner Left"),
                    ("NEW_MESSAGE", "New Message"),
                    ("GIVEAWAY_OFFER_SENT", "Giveaway Offer Sent"),
                    ("GIVEAWAY_ACCEPTED", "Giveaway Accepted"),
                    ("GIVEAWAY_DECLINED", "Giveaway Declined"),
                    ("GIVEAWAY_REQUEST_RECEIVED", "Giveaway Request Received"),
                    ("GIVEAWAY_REQUEST_APPROVED", "Giveaway Request Approved"),
                    ("GIVEAWAY_REQUEST_DECLINED", "Giveaway Request Declined"),
                    ("GIVEAWAY_COMPLETED", "Giveaway Completed"),
                ],
                max_length=100,
            ),
        ),
    ]
