# Generated by Django 5.2.13 on 2026-09-10 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_messaging", "0005_chatthread_read_cursors"),
        ("borrowd_notifications", "0006_seed_community_request_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ITEM_REQUESTED", "Item Requested"),
                    ("ITEM_REQUEST_ACCEPTED", "Item Request Accepted"),
                    ("ITEM_REQUEST_DENIED", "Item Request Denied"),
                    ("COLLECTION_ASSERTED", "Collection Asserted"),
                    ("COLLECTION_CONFIRMED", "Collection Confirmed"),
                    ("RETURN_ASSERTED", "Return Asserted"),
                    ("RETURN_CONFIRMED", "Return Confirmed"),
                    ("ITEM_NOTIFY_WHEN_AVAILABLE", "Item Notify When Available"),
                    ("ITEM_SUBSCRIPTION", "Item Subscription"),
                    ("ITEM_RETURN_REQUESTED", "Item Return Requested"),
                    ("ITEM_DISPUTED", "Item Disputed"),
                    ("GROUP_MEMBER_JOINED", "Group Member Joined"),
                    ("GROUP_NEEDS_MODERATOR", "Group Needs Moderator"),
                    ("MEMBERSHIP_PENDING", "Membership Pending"),
                    ("MEMBERSHIP_APPROVED", "Membership Approved"),
                    ("COMMUNITY_REQUEST_POSTED", "Community Request Posted"),
                    ("COMMUNITY_REQUEST_FULFILLED", "Community Request Fulfilled"),
                    (
                        "REQUEST_CANCELLED_BORROWER_LEFT",
                        "Request Cancelled Borrower Left",
                    ),
                    ("REQUEST_CANCELLED_OWNER_LEFT", "Request Cancelled Owner Left"),
                    ("LOAN_ENDED_OWNER_LEFT", "Loan Ended Owner Left"),
                    ("NEW_MESSAGE", "New Message"),
                    ("GIVEAWAY_OFFER_SENT", "Giveaway Offer Sent"),
                    ("GIVEAWAY_ACCEPTED", "Giveaway Accepted"),
                    ("GIVEAWAY_DECLINED", "Giveaway Declined"),
                    ("GIVEAWAY_REQUEST_RECEIVED", "Giveaway Request Received"),
                    ("GIVEAWAY_REQUEST_APPROVED", "Giveaway Request Approved"),
                    ("GIVEAWAY_REQUEST_DECLINED", "Giveaway Request Declined"),
                    ("GIVEAWAY_COMPLETED", "Giveaway Completed"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ConversationNudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLEARED", "Cleared")],
                        default="ACTIVE",
                        help_text="Whether this nudge can still be refreshed.",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this notification cycle started.",
                    ),
                ),
                (
                    "cleared_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the recipient read through the covered message.",
                        null=True,
                    ),
                ),
                (
                    "latest_message",
                    models.ForeignKey(
                        help_text="Newest message covered by this nudge.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="borrowd_messaging.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who may receive this conversation notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_nudges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Conversation represented by this nudge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_nudges",
                        to="borrowd_messaging.chatthread",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("recipient", "thread"),
                        name="unique_active_nudge_per_recipient_thread",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("cleared_at__isnull", True), ("status", "ACTIVE")
                            ),
                            models.Q(
                                ("cleared_at__isnull", False), ("status", "CLEARED")
                            ),
                            _connector="OR",
                        ),
                        name="conversation_nudge_clear_time_matches_status",
                    ),
                ],
            },
        ),
    ]
