# Generated by Django 5.2 on 2025-05-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="trust_level_required",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                default=1,
                help_text="The minimum required Group trust level required for this Item to be visible to and borrowable by members of that Group.",
            ),
            preserve_default=False,
        ),
    ]
