# Generated by Django 5.2 on 2025-05-18 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0004_itemphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.IntegerField(
                choices=[(10, "Available"), (20, "Reserved"), (30, "Borrowed")],
                default=10,
                help_text="The current status of the Item.",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Requested"),
                            (20, "Rejected"),
                            (30, "Accepted"),
                            (40, "Collection Asserted"),
                            (50, "Collected"),
                            (60, "Return Asserted"),
                            (70, "Returned"),
                        ],
                        default=10,
                        help_text="The current status of the Transaction.",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The Item which is the subject of the Transaction.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "party1",
                    models.ForeignKey(
                        help_text="The first party in the Transaction: 'lender', 'giver', 'owner', etc.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party2",
                    models.ForeignKey(
                        help_text="The second party in the Transaction: 'borrower', 'receiver', etc.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="The User who last updated the Transaction.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
