# Generated by Django 5.2 on 2025-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0005_item_status_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Requested"),
                    (20, "Rejected"),
                    (30, "Accepted"),
                    (40, "Collection Asserted"),
                    (50, "Collected"),
                    (60, "Return Asserted"),
                    (70, "Returned"),
                    (80, "Cancelled"),
                ],
                default=10,
                help_text="The current status of the Transaction.",
            ),
        ),
    ]
