# Generated by Django 5.2.1 on 2025-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0007_transaction_created_at_transaction_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="trust_level_required",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                default=3,
                help_text="The minimum required Group trust level required for this Item to be visible to and borrowable by members of that Group.",
            ),
        ),
    ]
