# Generated by Django 5.2.1 on 2025-11-15 15:22

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0008_alter_item_trust_level_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemphoto",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="items/"),
        ),
    ]
