# Generated by Django 5.2.1 on 2025-12-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0009_alter_itemphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories this item belongs to. At least one required.",
                related_name="items",
                to="borrowd_items.itemcategory",
            ),
        ),
    ]
