# Generated by Django 5.2.1 on 2025-12-10 11:30

from typing import Any

from django.db import migrations


# https://docs.djangoproject.com/en/5.2/ref/migration-operations/#runpython
def migrate_category_to_categories(apps: Any, schema_editor: Any) -> None:
    """Copy old single category FK to new categories M2M field."""
    Item = apps.get_model("borrowd_items", "Item")
    for item in Item.objects.filter(category__isnull=False):
        item.categories.add(item.category)


def reverse_migrate_categories_to_category(apps: Any, schema_editor: Any) -> None:
    """Reverse: copy first category from M2M back to FK."""
    Item = apps.get_model("borrowd_items", "Item")
    for item in Item.objects.all():
        first_category = item.categories.first()
        if first_category:
            item.category = first_category
            item.save(update_fields=["category"])


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0010_add_categories_m2m_field"),
    ]

    operations = [
        migrations.RunPython(
            migrate_category_to_categories,
            reverse_migrate_categories_to_category,
        ),
    ]
