# Generated by Django 5.2.1 on 2025-12-10 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0011_migrate_category_to_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
    ]
