# Generated by Django 5.2.1 on 2026-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0012_remove_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="trust_level_required",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "High")],
                default=1,
                help_text="The minimum required Group trust level required for this Item to be visible to and borrowable by members of that Group.",
            ),
        ),
    ]
