# Generated by Django 5.2.1 on 2026-02-11 10:53

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_item_trust_level(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Item = apps.get_model("borrowd_items", "Item")
    for item in Item.objects.all():
        if item.trust_level_required == 3:
            item.trust_level_required = 2
        elif item.trust_level_required == 2:
            item.trust_level_required = 1
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0012_remove_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="trust_level_required",
            field=models.IntegerField(
                choices=[(1, "Standard"), (2, "High")],
                default=1,
                help_text="The minimum required Group trust level required for this Item to be visible to and borrowable by members of that Group.",
            ),
        ),
        migrations.RunPython(update_item_trust_level),
    ]
