# Generated by Django 5.2.1 on 2026-03-09 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0013_alter_item_trust_level_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Active"),
                            (20, "Notified"),
                            (30, "Cancelled"),
                            (40, "Expired"),
                        ],
                        default=10,
                        help_text="The current status of the Subscription.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this Subscription was created.",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user was notified that the item became available.",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="The user's preferred language for notifications (e.g. 'en', 'fr', etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The Item which is the subject of the Subscription.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The User who is subscribed to the Item.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", 10)),
                        fields=("item", "user"),
                        name="unique_active_subscription_per_user_and_item",
                    )
                ],
            },
        ),
    ]
