# Generated by Django 5.2.13 on 2026-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0018_audit_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_account_deleted", "Owner closed their account"),
                    ("moderator_override", "Resolved by a moderator"),
                    ("counterparty_unresponsive", "Other party was unresponsive"),
                ],
                default=None,
                help_text="Why the Transaction was force-resolved outside the normal dual-confirmation flow. NULL for normally-completed Transactions.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Requested"),
                    (20, "Rejected"),
                    (30, "Accepted"),
                    (40, "Collection Asserted"),
                    (50, "Collected"),
                    (60, "Return Asserted"),
                    (70, "Returned"),
                    (80, "Cancelled"),
                    (90, "Resolved"),
                ],
                default=10,
                help_text="The current status of the Transaction.",
            ),
        ),
    ]
