# Generated by Django 5.2.13 on 2026-06-09 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0019_transaction_resolution_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="dispute_raised_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Who raised the dispute. NULL means never disputed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="disputed_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the Transaction entered DISPUTED. Survives resolution as a durable record that a dispute occurred. NULL means never disputed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="return_requested_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the lender requested return of the item. Anchors the dispute wait window. NULL means no return request was made.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Requested"),
                    (20, "Rejected"),
                    (30, "Accepted"),
                    (40, "Collection Asserted"),
                    (50, "Collected"),
                    (55, "Return Requested"),
                    (60, "Return Asserted"),
                    (65, "Disputed"),
                    (70, "Returned"),
                    (80, "Cancelled"),
                    (90, "Resolved"),
                ],
                default=10,
                help_text="The current status of the Transaction.",
            ),
        ),
    ]
