# Generated by Django 5.2.13 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0020_transaction_dispute_raised_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="disputed_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the Transaction entered DISPUTED. NULL means never disputed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_account_deleted", "Owner closed their account"),
                    ("moderator_override", "Resolved by a moderator"),
                    ("counterparty_unresponsive", "Other party was unresponsive"),
                    ("dispute_item_not_returned", "Disputed item was not returned"),
                ],
                default=None,
                help_text="Why the Transaction was force-resolved outside the normal dual-confirmation flow. NULL for normally-completed Transactions.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="return_requested_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the lender requested the return of the item. Wait window starts from this time. NULL means no return request was made.",
                null=True,
            ),
        ),
    ]
