# Generated by Django 5.2.13 on 2026-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0021_alter_transaction_disputed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Requested"),
                    (20, "Rejected"),
                    (30, "Accepted"),
                    (40, "Collection Asserted"),
                    (50, "Collected"),
                    (52, "Giveaway Offered"),
                    (55, "Return Requested"),
                    (60, "Return Asserted"),
                    (65, "Disputed"),
                    (70, "Returned"),
                    (80, "Cancelled"),
                    (90, "Resolved"),
                    (95, "Ownership Transferred"),
                ],
                default=10,
                help_text="The current status of the Transaction.",
            ),
        ),
    ]
