# Generated by Django 5.2.13 on 2026-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0022_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="listing_type",
            field=models.IntegerField(
                choices=[(10, "Lend"), (20, "Give away")],
                default=10,
                help_text="Whether this Item is offered for borrowing or as a giveaway a group member can request to keep.",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Requested"),
                    (15, "Giveaway Requested"),
                    (20, "Rejected"),
                    (30, "Accepted"),
                    (40, "Collection Asserted"),
                    (50, "Collected"),
                    (52, "Giveaway Offered"),
                    (55, "Return Requested"),
                    (60, "Return Asserted"),
                    (65, "Disputed"),
                    (70, "Returned"),
                    (80, "Cancelled"),
                    (90, "Resolved"),
                    (95, "Ownership Transferred"),
                ],
                default=10,
                help_text="The current status of the Transaction.",
            ),
        ),
    ]
