# Generated by Django 5.2.13 on 2026-08-24 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0024_item_listing_type_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemphoto",
            options={"ordering": ["pk"]},
        ),
    ]
