# Generated by Django 5.2.17 on 2026-10-03 17:04

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

# OPEN_TRANSACTION_STATUSES as of this migration.
OPEN_STATUSES = (10, 15, 30, 40, 50, 52, 55, 60, 65)


def check_for_multiple_open_transactions(apps, schema_editor):
    """Fail with the item IDs to fix, rather than a bare IntegrityError."""
    Transaction = apps.get_model("borrowd_items", "Transaction")
    duplicates = list(
        Transaction.objects.using(schema_editor.connection.alias)
        .filter(status__in=OPEN_STATUSES)
        .values("item_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("item_id")[:20]
    )
    if duplicates:
        item_ids = ", ".join(str(row["item_id"]) for row in duplicates)
        raise RuntimeError(
            "Cannot add unique_open_transaction_per_item: items "
            f"{item_ids} have more than one open transaction. Run "
            "audit_item_transactions, resolve them, and migrate again."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0025_alter_itemphoto_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            check_for_multiple_open_transactions, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", OPEN_STATUSES)),
                fields=("item",),
                name="unique_open_transaction_per_item",
            ),
        ),
    ]
