# Generated by Django 5.2.17 on 2026-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0026_unique_open_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                help_text="Advances on every change to the item or its transactions, so a client can tell that what it showed is out of date.",
            ),
        ),
    ]
