# Generated by Django 5.2.17 on 2026-10-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0027_item_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCommandRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(
                        help_text="Picked by the client, once per command it means to send."
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="What the command asked for, so a key sent with another one is caught.",
                        max_length=64,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REQUEST_ITEM", "Request Item"),
                            ("ACCEPT_REQUEST", "Accept Request"),
                            ("REJECT_REQUEST", "Reject Request"),
                            ("MARK_COLLECTED", "Mark Collected"),
                            ("CONFIRM_COLLECTED", "Confirm Collected"),
                            ("NOTIFY_WHEN_AVAILABLE", "Notify when available"),
                            (
                                "CANCEL_NOTIFICATION_REQUEST",
                                "Cancel notification request",
                            ),
                            ("MARK_RETURNED", "Mark Returned"),
                            ("CONFIRM_RETURNED", "Confirm Returned"),
                            ("CANCEL_REQUEST", "Cancel Request"),
                            ("RESOLVE_TRANSACTION", "Close Out Transaction"),
                            ("REQUEST_RETURN", "Request Return"),
                            ("FLAG_CANNOT_RETURN", "Cannot Return Item"),
                            ("RAISE_DISPUTE", "Raise Dispute"),
                            (
                                "RESOLVE_DISPUTE_RETURNED",
                                "Resolve Dispute: Item Returned",
                            ),
                            (
                                "RESOLVE_DISPUTE_NOT_RETURNED",
                                "Resolve Dispute: Item Not Returned",
                            ),
                            ("OFFER_GIVEAWAY", "Give Away"),
                            ("ACCEPT_GIVEAWAY", "Accept Gift"),
                            ("DECLINE_GIVEAWAY", "Decline Gift"),
                            ("REQUEST_GIVEAWAY", "Request Gift"),
                            ("APPROVE_GIVEAWAY_REQUEST", "Approve Giveaway Request"),
                            ("DECLINE_GIVEAWAY_REQUEST", "Decline Giveaway Request"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "Requested"),
                            (15, "Giveaway Requested"),
                            (20, "Rejected"),
                            (30, "Accepted"),
                            (40, "Collection Asserted"),
                            (50, "Collected"),
                            (52, "Giveaway Offered"),
                            (55, "Return Requested"),
                            (60, "Return Asserted"),
                            (65, "Disputed"),
                            (70, "Returned"),
                            (80, "Cancelled"),
                            (90, "Resolved"),
                            (95, "Ownership Transferred"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        help_text="The item's revision once the command was done."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="borrowd_items.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "key"),
                        name="unique_item_command_key_per_actor",
                    )
                ],
            },
        ),
    ]
