# Generated by Django 5.2.17 on 2026-10-03 20:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0028_item_command_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        help_text="The item's revision once the change was made. Orders a transaction's events."
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REQUEST_ITEM", "Request Item"),
                            ("ACCEPT_REQUEST", "Accept Request"),
                            ("REJECT_REQUEST", "Reject Request"),
                            ("MARK_COLLECTED", "Mark Collected"),
                            ("CONFIRM_COLLECTED", "Confirm Collected"),
                            ("NOTIFY_WHEN_AVAILABLE", "Notify when available"),
                            (
                                "CANCEL_NOTIFICATION_REQUEST",
                                "Cancel notification request",
                            ),
                            ("MARK_RETURNED", "Mark Returned"),
                            ("CONFIRM_RETURNED", "Confirm Returned"),
                            ("CANCEL_REQUEST", "Cancel Request"),
                            ("RESOLVE_TRANSACTION", "Close Out Transaction"),
                            ("REQUEST_RETURN", "Request Return"),
                            ("FLAG_CANNOT_RETURN", "Cannot Return Item"),
                            ("RAISE_DISPUTE", "Raise Dispute"),
                            (
                                "RESOLVE_DISPUTE_RETURNED",
                                "Resolve Dispute: Item Returned",
                            ),
                            (
                                "RESOLVE_DISPUTE_NOT_RETURNED",
                                "Resolve Dispute: Item Not Returned",
                            ),
                            ("OFFER_GIVEAWAY", "Give Away"),
                            ("ACCEPT_GIVEAWAY", "Accept Gift"),
                            ("DECLINE_GIVEAWAY", "Decline Gift"),
                            ("REQUEST_GIVEAWAY", "Request Gift"),
                            ("APPROVE_GIVEAWAY_REQUEST", "Approve Giveaway Request"),
                            ("DECLINE_GIVEAWAY_REQUEST", "Decline Giveaway Request"),
                        ],
                        help_text="The action behind the change. Blank for account closure or a forced resolution.",
                        max_length=50,
                    ),
                ),
                (
                    "source_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "Requested"),
                            (15, "Giveaway Requested"),
                            (20, "Rejected"),
                            (30, "Accepted"),
                            (40, "Collection Asserted"),
                            (50, "Collected"),
                            (52, "Giveaway Offered"),
                            (55, "Return Requested"),
                            (60, "Return Asserted"),
                            (65, "Disputed"),
                            (70, "Returned"),
                            (80, "Cancelled"),
                            (90, "Resolved"),
                            (95, "Ownership Transferred"),
                        ],
                        help_text="NULL when the change opened the transaction.",
                        null=True,
                    ),
                ),
                (
                    "target_status",
                    models.IntegerField(
                        choices=[
                            (10, "Requested"),
                            (15, "Giveaway Requested"),
                            (20, "Rejected"),
                            (30, "Accepted"),
                            (40, "Collection Asserted"),
                            (50, "Collected"),
                            (52, "Giveaway Offered"),
                            (55, "Return Requested"),
                            (60, "Return Asserted"),
                            (65, "Disputed"),
                            (70, "Returned"),
                            (80, "Cancelled"),
                            (90, "Resolved"),
                            (95, "Ownership Transferred"),
                        ]
                    ),
                ),
                (
                    "command_key",
                    models.UUIDField(
                        blank=True,
                        help_text="The client's command key, if it sent one.",
                        null=True,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once retries ran out. Holds back the transaction's later events until replayed or skipped.",
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("skip_reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "skipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="borrowd_items.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LifecycleEventConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer", models.CharField(max_length=50)),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="borrowd_items.lifecycleevent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lifecycleevent",
            index=models.Index(
                fields=["transaction", "revision"], name="lifecycle_event_order"
            ),
        ),
        migrations.AddIndex(
            model_name="lifecycleevent",
            index=models.Index(
                condition=models.Q(("processed_at__isnull", True)),
                fields=["next_attempt_at"],
                name="lifecycle_event_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifecycleeventconsumption",
            constraint=models.UniqueConstraint(
                fields=("consumer", "event"), name="unique_event_per_consumer"
            ),
        ),
    ]
