# Generated by Django 5.2.17 on 2026-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_items", "0029_lifecycle_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifecycleevent",
            name="schema_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
