# Generated by Django 5.2.1 on 2025-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="display_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="last", max_length=50),
            preserve_default=False,
        ),
    ]
