# Generated by Django 5.2.1 on 2025-10-06 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0002_rename_display_name_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
