# Generated by Django 5.2.1 on 2025-10-27 23:16

from django.db import migrations, models


def forwards_func(apps, schema_editor):  # type: ignore[no-untyped-def]
    BorrowdUser = apps.get_model("borrowd_users", "BorrowdUser")
    for bu in BorrowdUser.objects.all():
        bu.first_name = bu.profile.first_name or "First"
        bu.last_name = bu.profile.last_name or "Last"
        bu.save()


def reverse_func(apps, schema_editor):  # type: ignore[no-untyped-def]
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0002_rename_display_name_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowduser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="borrowduser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
