# Generated by Django 5.2.1 on 2025-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0003_remove_profile_first_name_remove_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowduser",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="borrowduser",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
