# Generated by Django 5.2.1 on 2025-11-15 15:22

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowd_users",
            "0004_remove_profile_first_name_remove_profile_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="profile_pics/"
            ),
        ),
    ]
