# Generated by Django 5.2.1 on 2025-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
