# Generated by Django 5.2.1 on 2026-04-09 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowd_users', '0009_increase_bio_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBadgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_count', models.PositiveIntegerField(default=0)),
                ('groups_count', models.PositiveIntegerField(default=0)),
                ('hamburger_dot_visible', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_badge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
