# Generated by Django 5.2.1 on 2026-04-09 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowd_users', '0010_menubadgestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubadgestate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
