# Generated by Django 5.2.13 on 2026-08-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowd_users",
            "0011_borrowduser_created_at_borrowduser_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_pre_request_chat",
            field=models.BooleanField(
                default=True,
                help_text="Whether other users can message this user about their items before making a request.",
            ),
        ),
    ]
