# Generated by Django 5.2.17 on 2026-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0012_profile_allow_pre_request_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="join_group_nudge_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has already been shown the one-time nudge to join a group after adding an item while in no active group.",
            ),
        ),
    ]
