# Generated by Django 5.2.17 on 2026-10-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0013_profile_join_group_nudge_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="add_profile_photo_nudge_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has already been shown the one-time nudge to add a profile photo after creating a group while having none.",
            ),
        ),
    ]
