# Generated by Django 5.2.17 on 2026-10-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_users", "0014_profile_add_profile_photo_nudge_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="invite_friends_nudge_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has already been shown the one-time nudge to invite friends to their group after adding a profile photo.",
            ),
        ),
    ]
