# Generated by Django 5.2.13 on 2026-08-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import borrowd_permissions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowd_items", "0024_item_listing_type_alter_transaction_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Set when the thread becomes read-only. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "archive_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("returned", "Returned"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("resolved", "Resolved"),
                            ("ownership_transferred", "Ownership Transferred"),
                            ("item_unavailable", "Item Unavailable"),
                            ("item_deleted", "Item Deleted"),
                            ("closed", "Closed"),
                        ],
                        default=None,
                        help_text="Why the thread was archived. NULL for active threads.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "lender_last_read_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the lender last opened the thread. NULL means never.",
                        null=True,
                    ),
                ),
                (
                    "borrower_last_read_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the borrower last opened the thread. NULL means never.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time at which the thread was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time at which the thread was last updated.",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        help_text="The user who opened (or requested via) this thread.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created the thread.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The Item under discussion. NULL after the item is hard-deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_threads",
                        to="borrowd_items.item",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        help_text="The item's owner at thread creation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text="The Transaction this thread belongs to. NULL while the thread is in the pre-request phase.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_thread",
                        to="borrowd_items.transaction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="The last user who updated the thread.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        borrowd_permissions.models.ChatThreadOLP["VIEW"],
                        "Can view this chat thread",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("archived_at__isnull", True), ("transaction__isnull", True)
                        ),
                        fields=("borrower", "item"),
                        name="one_active_prerequest_thread_per_borrower_item",
                    )
                ],
            },
        ),
    ]
