# Generated by Django 5.2.13 on 2026-08-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True for messages the app posts itself, e.g. archival notices.",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        help_text="The message text. Plain text only.", max_length=2000
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was sent."
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Who wrote the message. The system user for system messages.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this message belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="borrowd_messaging.chatthread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["thread", "id"], name="msg_thread_cursor_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="message_body_not_empty",
                    )
                ],
            },
        ),
    ]
