# Generated by Django 5.2.13 on 2026-09-01 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_groups", "0014_alter_borrowdgroup_banner_alter_borrowdgroup_logo"),
        ("borrowd_items", "0025_alter_itemphoto_options"),
        ("borrowd_messaging", "0002_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="conversation_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The group this conversation was filed under, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="borrowd_groups.borrowdgroup",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="conversation_group_name",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The selected group's name at conversation creation.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="conversation_group_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=None,
                help_text="The selected group's ID at conversation creation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="listing_type",
            field=models.IntegerField(
                blank=True,
                choices=[(10, "Lend"), (20, "Give away")],
                default=None,
                help_text="The Item's listing type at conversation creation.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversation_group__isnull", True),
                        ("conversation_group_name__isnull", True),
                        ("conversation_group_source_id__isnull", True),
                    ),
                    models.Q(
                        ("conversation_group_name__isnull", False),
                        ("conversation_group_source_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chat_thread_group_context_is_consistent",
            ),
        ),
    ]
