# Generated by Django 5.2.13 on 2026-09-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_messaging", "0004_backfill_conversation_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatthread",
            name="borrower_last_read_at",
        ),
        migrations.RemoveField(
            model_name="chatthread",
            name="lender_last_read_at",
        ),
        migrations.AddField(
            model_name="chatthread",
            name="borrower_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the borrower has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="lender_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the lender has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
    ]
