# Generated by Django 5.2.13 on 2026-09-06 23:49

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import OuterRef, Subquery


def backfill_read_cursors(
    apps: StateApps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """Point each cursor at the last message sent by the read cutoff, if any."""
    ChatThread = apps.get_model("borrowd_messaging", "ChatThread")
    Message = apps.get_model("borrowd_messaging", "Message")
    database = schema_editor.connection.alias

    for cursor_field, cutoff_field in (
        ("lender_last_read_message", "lender_last_read_at"),
        ("borrower_last_read_message", "borrower_last_read_at"),
    ):
        last_read_message = (
            Message.objects.using(database)
            .filter(thread_id=OuterRef("pk"), created_at__lte=OuterRef(cutoff_field))
            .order_by("-id")
            .values("pk")[:1]
        )
        (
            ChatThread.objects.using(database)
            .filter(**{f"{cutoff_field}__isnull": False})
            .update(**{cursor_field: Subquery(last_read_message)})
        )


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_messaging", "0004_backfill_conversation_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="borrower_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the borrower has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="lender_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the lender has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
        migrations.RunPython(backfill_read_cursors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="chatthread",
            name="borrower_last_read_at",
        ),
        migrations.RemoveField(
            model_name="chatthread",
            name="lender_last_read_at",
        ),
    ]
