# Generated by Django 5.2.13 on 2026-09-14 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowd_messaging", "0005_chatthread_read_cursors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatthread",
            name="borrower_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the borrower has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="lender_last_read_message",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The greatest message the lender has acknowledged rendering.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="borrowd_messaging.message",
            ),
        ),
    ]
